classes:
  QObject: Object
  QTimer: Timer
  "QMetaObject::Connection": SignalConnection
  QAbstractEventDispatcher: AbstractEventDispatcher
  QAbstractEventDispatcher::TimerInfo: EventDispatcherTimerInfo
  QSocketNotifier: SocketNotifier
  QPaintDevice: PaintDevice
  QWidget: Widget
  QAbstractButton: AbstractButton
  QToolButton: ToolButton
  QToolBar: ToolBar
  QFrame: Frame
  QComboBox: ComboBox
  QProgressBar: ProgressBar
  QAbstractSlider: AbstractSlider
  QDial: Dial
  QScrollBar: ScrollBar
  QSlider: Slider
  QAbstractScrollArea: AbstractScrollArea
  QScrollArea: ScrollArea
  QAbstractSpinBox: AbstractSpinBox
  QSpinBox: SpinBox
  QDoubleSpinBox: DoubleSpinBox
  QDateTimeEdit: DateTimeEdit
  QMenuBar: MenuBar
  QMenu: Menu
  QAction: Action
  QCompleter: Completer
  QStatusBar: StatusBar
  QMainWindow: MainWindow
  QDockWidget: DockWidget
  QDialog: Dialog
  QLabel: Label
  QLCDNumber: LcdNumber
  QPushButton: PushButton
  QCheckBox: CheckBox
  QRadioButton: RadioButton
  QButtonGroup: ButtonGroup
  QGroupBox: GroupBox
  QCoreApplication: CoreApplication
  QGuiApplication: GuiApplication
  QApplication: Application
  QVariant: Variant
  QImage: Image
  QPixmap: Pixmap
  QBitmap: Bitmap
  QIcon: Icon
  QEventLoop: EventLoop
  QTabBar: TabBar
  QTabWidget: TabWidget
  QModelIndex: ModelIndex
  QAbstractItemView: AbstractItemView
  QAbstractItemModel: AbstractItemModel
  QStandardItemModel: StandardItemModel
  QAbstractListModel: AbstractListModel
  QTableView: TableView
  QTableWidget: TableWidget
  QTableWidgetItem: TableWidgetItem
  QAbstractItemDelegate: AbstractItemDelegate
  QStyledItemDelegate: StyledItemDelegate
  QItemEditorFactory: ItemEditorFactory
  QLayoutItem: LayoutItem
  QSpacerItem: SpacerItem
  QWidgetItem: WidgetItem
  QLayout: Layout
  QBoxLayout: BoxLayout
  QHBoxLayout: HBoxLayout
  QVBoxLayout: VBoxLayout
  QGridLayout: GridLayout
  QStackedLayout: StackedLayout
  QFormLayout: FormLayout
  QPalette: Palette
  QPoint: Point
  QPointF: PointF
  QRect: Rect
  QRectF: RectF
  QKeySequence: KeySequence
  QLineEdit: LineEdit
  QTextEdit: TextEdit
  QFileDialog: FileDialog
  QTextOption: TextOption
  # "QTextOption::Tab": TextOptionTab
  QTextDocument: TextDocument
  QTextCursor: TextCursor
  QCursor: Cursor
  QDir: Dir
  QGraphicsItem: GraphicsItem
  QGraphicsScene: GraphicsScene
  QGraphicsView: GraphicsView
  QGraphicsObject: GraphicsObject
  QGraphicsWidget: GraphicsWidget
  QGraphicsTextItem: GraphicsTextItem
  QGraphicsTransform: GraphicsTransform
  QAbstractGraphicsShapeItem: AbstractGraphicsShapeItem
  QGraphicsEllipseItem: GraphicsEllipseItem
  QGraphicsPathItem: GraphicsPathItem
  QGraphicsPolygonItem: GraphicsPolygonItem
  QGraphicsRectItem: GraphicsRectItem
  QGraphicsSimpleTextItem: GraphicsSimpleTextItem
  QGraphicsPixmapItem: GraphicsPixmapItem
  QBrush: Brush
  QColor: Color
  QEvent: Event
  QTimerEvent: TimerEvent
  QDynamicPropertyChangeEvent: DynamicPropertyChangeEvent
  QDeferredDeleteEvent: DeferredDeleteEvent
  QInputEvent: InputEvent
  QKeyEvent: KeyEvent
  QMouseEvent: MouseEvent
  QEnterEvent: EnterEvent
  QFocusEvent: FocusEvent
  QPaintEvent: PaintEvent
  QMoveEvent: MoveEvent
  QExposeEvent: ExposeEvent
  QPlatformSurfaceEvent: PlatformSurfaceEvent
  QResizeEvent: ResizeEvent
  QCloseEvent: CloseEvent
  QIconDragEvent: IconDragEvent
  QShowEvent: ShowEvent
  QHideEvent: HideEvent
  QInputMethodEvent: InputMethodEvent
  # "QInputMethodEvent::Attribute": InputMethodEventAttribute # Bare struct, contains QVariant
  QInputMethodQueryEvent: InputMethodQueryEvent
  QDrag: Drag
  QDropEvent: DropEvent
  QDragMoveEvent: DragMoveEvent
  QDragEnterEvent: DragEnterEvent
  QDragLeaveEvent: DragLeaveEvent
  QHelpEvent: HelpEvent
  QStatusTipEvent: StatusTipEvent
  QWhatsThisClickedEvent: WhatsThisClickedEvent
  QActionEvent: ActionEvent
  QFileOpenEvent: FileOpenEvent
  QToolBarChangeEvent: ToolBarChangeEvent
  QShortcutEvent: ShortcutEvent
  QScrollPrepareEvent: ScrollPrepareEvent
  QScrollEvent: ScrollEvent
  QScreenOrientationChangeEvent: ScreenOrientationChangeEvent
  QApplicationStateChangeEvent: ApplicationStateChangeEvent
  QGestureEvent: GestureEvent
  QGraphicsSceneEvent: GraphicsSceneEvent
  QIODevice: IODevice
  QGesture: Gesture
  QPainter: Painter
  # "QPainter::PixmapFragment": PainterPixmapFragment
  QLine: QLine
  QLineF: QLineF
  QSystemTrayIcon: SystemTrayIcon
  QDesktopServices: DesktopServices
  QDesktopWidget: DesktopWidget
  QStandardPaths: StandardPaths
  QMimeData: MimeData
  QSizePolicy: SizePolicy
  QUrl: Url
  QScreen: Screen
  QSurface: Surface
  QWindow: Window
  QPixelFormat: PixelFormat
  QTextFormat: TextFormat
  QTextBlockFormat: TextBlockFormat
  QTextCharFormat: TextCharFormat
  QTextFrameFormat: TextFrameFormat
  QTextListFormat: TextListFormat
  QTextLength: TextLength
  QFont: Font
  QFontMetrics: FontMetrics
  QStyleOptionGraphicsItem: StyleOptionGraphicsItem
  QListView: ListView
  QSize: Size
  QListWidget: ListWidget
  QListWidgetItem: ListWidgetItem
  QMargins: Margins
  QMetaObject: MetaObject
