enums:
  "Qt::CheckState": CheckState
  "Qt::ConnectionType": ConnectionType
  "Qt::TimerType": TimerType
  "Qt::GestureType": GestureType
  "Qt::GestureFlags": GestureFlags
  "Qt::LayoutDirection": LayoutDirection
  "Qt::FocusReason": FocusReason
  "Qt::FocusPolicy": FocusPolicy
  "Qt::ContextMenuPolicy": ContextMenuPolicy
  "Qt::BrushStyle": BrushStyle
  "Qt::ShortcutContext": ShortcutContext
  "Qt::WindowFlags": WindowFlags
  "Qt::WindowModality": WindowModality
  "Qt::WindowStates": WindowStates
  "Qt::WindowType": WindowType
  "Qt::InputMethodQuery": InputMethodQuery
  "Qt::InputMethodHints": InputMethodHints
  "Qt::TextFormat": TextFormatEnum # This collides with class `QTextFormat` -> `TextFormat`...
  "Qt::Alignment": Alignment
  "Qt::TextInteractionFlags": TextInteractionFlags
  "Qt::UIEffect": UIEffect
  "Qt::ApplicationAttribute": ApplicationAttribute
  "Qt::ScrollBarPolicy": ScrollBarPolicy
  "Qt::ItemSelectionMode": ItemSelectionMode
  "Qt::SortOrder": SortOrder
  "Qt::ItemSelectionOperation": ItemSelectionOperation
  "Qt::SizeHint": SizeHint
  "Qt::WindowFrameSection": WindowFrameSection
  "Qt::CursorMoveStyle": CursorMoveStyle
  "Qt::CursorShape": CursorShape
  "QEventLoop::ProcessEventsFlags": EventLoop::ProcessEventsFlags
  "Qt::KeyboardModifiers": KeyboardModifiers
  "Qt::MouseButtons": MouseButtons
  "Qt::ApplicationState": ApplicationState
  "Qt::FillRule": FillRule
  "Qt::BGMode": BgMode
  "Qt::SizeMode": SizeMode
  "Qt::ClipOperation": ClipOperation
  "Qt::PenStyle": PenStyle
  "Qt::ScreenOrientations": ScreenOrientations
  "Qt::ArrowType": ArrowType
  "Qt::CaseSensitivity": CaseSensitivity
  "Qt::MatchFlags": MatchFlags
  "QVariant::Type": VariantType
  "QSocketNotifier::Type": SocketNotifier::Type
  "QSizePolicy::ControlType": SizePolicy::ControlType
  "QSizePolicy::ControlTypes": SizePolicy::ControlTypes
  "QSizePolicy::Policy": SizePolicy::Policy
  "QSizePolicy::PolicyFlag": SizePolicy::PolicyFlag
  "Qt::WidgetAttribute": WidgetAttribute
  "QPalette::ColorGroup": Palette::ColorGroup
  "QPalette::ColorRole": Palette::ColorRole
  "QWidget::RenderFlags": Widget::RenderFlags
  "QOpenGLWidget::UpdateBehavior": OpenGLWidget::UpdateBehavior
  "QOpenGLContext::OpenGLModuleType": OpenGLContext::OpenGLModuleType
  "QProgressBar::Direction": ProgressBar::Direction
  "QToolButton::ToolButtonPopupMode": ToolButton::ToolButtonPopupMode
  "QFrame::Shape": Frame::Shape
  "QFrame::Shadow": Frame::Shadow
  "QComboBox::InsertPolicy": ComboBox::InsertPolicy
  "QComboBox::SizeAdjustPolicy": ComboBox::SizeAdjustPolicy
  "QImage::Format": { destination: "Image::Format", prefix: "Format_" }
  "Qt::ImageConversionFlags": ImageConversionFlags
  "Qt::GlobalColor": GlobalColor
  "Qt::MaskMode": MaskMode
  "Qt::AspectRatioMode": AspectRatioMode
  "Qt::TransformationMode": TransformationMode
  "QImage::InvertMode": Image::InvertMode
  "QLCDNumber::Mode": LcdNumber::Mode
  "QLCDNumber::SegmentStyle": LcdNumber::SegmentStyle
  "QTabWidget::TabShape": TabWidget::TabShape
  "QTabWidget::TabPosition": TabWidget::TabPosition
  "QTabBar::ButtonPosition": TabBar::ButtonPosition
  "QTabBar::SelectionBehavior": TabBar::SelectionBehavior
  "QTabBar::Shape": TabBar::Shape
  "Qt::Corner": Corner
  "Qt::TextElideMode": TextElideMode
  "Qt::ToolButtonStyle": ToolButtonStyle
  "Qt::ToolBarArea": ToolBarArea
  "Qt::ToolBarAreas": ToolBarAreas
  "Qt::DockWidgetArea": DockWidgetArea
  "Qt::DockWidgetAreas": DockWidgetAreas
  "Qt::Orientation": Orientation
  "Qt::Orientations": Orientations
  "Qt::TimeSpec": TimeSpec
  "Qt::WindowState": WindowState
  "Qt::Key": { destination: "Key", prefix: true, camelcase: false }
  "QMainWindow::DockOptions": MainWindow::DockOptions
  "QDockWidget::DockWidgetFeature": DockWidget::Feature
  "QDockWidget::DockWidgetFeatures": DockWidget::Features
  "QLayout::SizeConstraint": Layout::SizeConstraint
  "QBoxLayout::Direction": BoxLayout::Direction
  "QStackedLayout::StackingMode": StackedLayout::StackingMode
  "QFormLayout::FieldGrowthPolicy": FormLayout::FieldGrowthPolicy
  "QFormLayout::ItemRole": FormLayout::ItemRole
  "QFormLayout::RowWrapPolicy": FormLayout::RowWrapPolicy
  "Qt::FindChildOptions": FindChildOptions
  "QPaintDevice::PaintDeviceMetric": PaintDevice::PaintDeviceMetric
  "QAction::ActionEvent": Action::Event
  "QAction::MenuRole": Action::MenuRole
  "QAction::Priority": Action::Priority
  "QKeySequence::StandardKey": KeySequence::StandardKey
  "QKeySequence::SequenceFormat": KeySequence::SequenceFormat
  "QKeySequence::SequenceMatch": KeySequence::SequenceMatch
  "QGraphicsItem::GraphicsItemFlags": GraphicsItem::Flags
  "QGraphicsItem::GraphicsItemFlag": GraphicsItem::Flag
  "QGraphicsItem::GraphicsItemChange": GraphicsItem::Change
  "QGraphicsItem::CacheMode": GraphicsItem::CacheMode
  "QGraphicsItem::PanelModality": GraphicsItem::PanelModality
  "QGraphicsItem::Extension": GraphicsItem::Extension
  "QPainter::RenderHints": Painter::RenderHints
  "QPainter::RenderHint": Painter::RenderHint
  "QPainter::CompositionMode": Painter::CompositionMode
  "QPainter::PixmapFragmentHint": Painter::PixmapFragmentHint
  "QPainter::PixmapFragmentHints": Painter::PixmapFragmentHints
  "QGraphicsView::ViewportAnchor": GraphicsView::ViewportAnchor
  "QGraphicsView::ViewportUpdateMode": GraphicsView::ViewportUpdateMode
  "QGraphicsView::OptimizationFlags": GraphicsView::OptimizationFlags
  "QGraphicsView::OptimizationFlag": GraphicsView::OptimizationFlag
  "QGraphicsView::DragMode": GraphicsView::DragMode
  "QGraphicsView::CacheMode": GraphicsView::CacheMode
  "QGraphicsScene::ItemIndexMethod": GraphicsScene::ItemIndexMethod
  "QGraphicsScene::SceneLayer": GraphicsScene::SceneLayer
  "QGraphicsScene::SceneLayers": GraphicsScene::SceneLayers
  "QGraphicsPixmapItem::ShapeMode": GraphicsPixmapItem::ShapeMode
  "QAbstractSlider::SliderAction": AbstractSlider::SliderAction
  "QAbstractSlider::SliderChange": AbstractSlider::SliderChange
  "QSlider::TickPosition": Slider::TickPosition
  "QAbstractScrollArea::SizeAdjustPolicy": AbstractScrollArea::SizeAdjustPolicy
  "QAbstractSpinBox::ButtonSymbols": AbstractSpinBox::ButtonSymbols
  "QAbstractSpinBox::CorrectionMode": AbstractSpinBox::CorrectionMode
  "QAbstractSpinBox::StepEnabled": AbstractSpinBox::StepEnabled
  "QAbstractSpinBox::StepEnabledFlag": AbstractSpinBox::StepEnabledFlag
  "QDateTimeEdit::Sections": DateTimeEdit::Sections
  "QDateTimeEdit::Section": DateTimeEdit::Section
  "QLineEdit::ActionPosition": LineEdit::ActionPosition
  "QLineEdit::EchoMode": LineEdit::EchoMode
  "QTextEdit::AutoFormatting": TextEdit::AutoFormatting
  "QTextEdit::AutoFormattingFlag": TextEdit::AutoFormattingFlag
  "QTextEdit::LineWrapMode": TextEdit::LineWrapMode
  "QDialog::DialogCode": Dialog::DialogCode
  "QFileDialog::AcceptMode": FileDialog::AcceptMode
  "QFileDialog::DialogLabel": FileDialog::DialogLabel
  "QFileDialog::FileMode": FileDialog::FileMode
  "QFileDialog::Option": FileDialog::Option
  "QFileDialog::Options": FileDialog::Options
  "QFileDialog::ViewMode": FileDialog::ViewMode
  "QUrl::ComponentFormattingOption": Url::ComponentFormattingOption
  "QUrl::ComponentFormattingOptions": Url::ComponentFormattingOptions
  "QUrl::ParsingMode": Url::ParsingMode
  "QUrl::UrlFormattingOption": Url::UrlFormattingOption
  # "QUrl::FormattingOptions": This one is actually a `QUrlTwoFlags`.  Manually implemented.
  "QUrl::UserInputResolutionOption": Url::UserInputResolutionOption
  "QUrl::UserInputResolutionOptions": Url::UserInputResolutionOptions
  "QSurface::SurfaceClass": Surface::SurfaceClass
  "QSurface::SurfaceType": Surface::SurfaceType
  "QWindow::AncestorMode": Window::AncestorMode
  "QWindow::Visibility": Window::Visibility
  "QDir::Filters": Dir::Filters
  "QTextOption::Flags": TextOption::Flags
  "QTextOption::WrapMode": TextOption::WrapMode
  "QTextOption::TabType": TextOption::TabType
  "QTextDocument::MetaInformation": TextDocument::MetaInformation
  "QTextDocument::Stacks": TextDocument::Stacks
  "QTextDocument::FindFlags": TextDocument::FindFlags
  "QTextCursor::MoveOperation": TextCursor::MoveOperation
  "QTextCursor::MoveMode": TextCursor::MoveMode
  "QTextCursor::SelectionType": TextCursor::SelectionType
  "QTextListFormat::Style": TextListFormat::Style
  "QTextFrameFormat::Position": TextFrameFormat::Position
  "QTextFormat::FormatType": TextFormat::FormatType
  "QTextFormat::ObjectTypes": TextFormat::ObjectTypes
  "QTextFormat::PageBreakFlag": TextFormat::PageBreakFlag
  "QTextFormat::PageBreakFlags": TextFormat::PageBreakFlags
  "QTextFormat::Property": TextFormat::Property
  "QTextCharFormat::FontPropertiesInheritanceBehavior": TextCharFormat::FontPropertiesInheritanceBehavior
  "QTextCharFormat::UnderlineStyle": TextCharFormat::UnderlineStyle
  "QTextCharFormat::VerticalAlignment": TextCharFormat::VerticalAlignment
  "QTextFrameFormat::BorderStyle": TextFrameFormat::BorderStyle
  "QTextLength::Type": TextLength::Type
  "QDir::SortFlags": Dir::SortFlags
  "QColor::NameFormat": Color::NameFormat
  "QColor::Spec": Color::Spec
  "QEvent::Type": Event::Type
  "QInputMethodEvent::AttributeType": InputMethodEvent::AttributeType
  "QPlatformSurfaceEvent::SurfaceEventType": PlatformSurfaceEvent::SurfaceEventType
  "Qt::InputMethodQueries": InputMethodQueries
  "Qt::DropActions": DropActions
  "Qt::DropAction": DropAction
  "QIODevice::OpenMode": IODevice::OpenMode
  "QScrollEvent::ScrollState": ScrollEvent::ScrollState
  "Qt::ScreenOrientation": ScreenOrientation
  "Qt::GestureState": GestureState
  "QGesture::GestureCancelPolicy": Gesture::GestureCancelPolicy
  "Qt::MouseButton": MouseButton
  "Qt::MouseEventSource": MouseEventSource
  "Qt::MouseEventFlags": MouseEventFlags
  "QIcon::Mode": Icon::Mode
  "QIcon::State": Icon::State
  "QSystemTrayIcon::ActivationReason": SystemTrayIcon::ActivationReason
  "QSystemTrayIcon::MessageIcon": SystemTrayIcon::MessageIcon
  "QStandardPaths::LocateOption": StandardPaths::LocateOption
  "QStandardPaths::LocateOptions": StandardPaths::LocateOptions
  "QStandardPaths::StandardLocation": StandardPaths::StandardLocation
  "QMetaObject::Call": MetaObjectCall
  "QPixelFormat::ByteOrder": PixelFormat::ByteOrder
  "QPixelFormat::ColorModel": PixelFormat::ColorModel
  "QPixelFormat::AlphaUsage": PixelFormat::AlphaUsage
  "QPixelFormat::AlphaPosition": PixelFormat::AlphaPosition
  "QPixelFormat::AlphaPremultiplied": PixelFormat::AlphaPremultiplied
  "QPixelFormat::TypeInterpretation": PixelFormat::TypeInterpretation
  "QPixelFormat::YUVLayout": PixelFormat::YUVLayout
  "QFont::Capitalization": Font::Capitalization
  "QFont::HintingPreference": Font::HintingPreference
  "QFont::SpacingType": Font::SpacingType
  "QFont::Stretch": Font::Stretch
  "QFont::Style": Font::Style
  "QFont::StyleHint": Font::StyleHint
  "QFont::StyleStrategy": Font::StyleStrategy
  "QFont::Weight": Font::Weight
